name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      say:
        description: 'what to say'
        type: string
jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "echo ${{ inputs.say }}"
